# LLM Configurations
llms:
  default_chat_model:
    provider: "gemini" # LLM provider (e.g., OpenAI, Azure, Anthropic, Google)
    model_name: "gemini-2.5-flash-preview-04-17" # Primary model for general user interactions
    temperature: 0.7

  routing_model:
    provider: "gemini"
    model_name: "gemini-2.5-flash-preview-04-17" # Lightweight model for routing incoming queries
    temperature: 0.0

  solar_query_model:
    provider: "gemini"
    model_name: "gemini-2.5-flash-preview-04-17" # Specialized model for handling solar-related queries
    temperature: 0.5

  dfp_query_model:
    provider: "gemini"
    model_name: "gemini-2.5-flash-preview-04-17" # Specialized model for handling DFP-related queries
    temperature: 0.5

query_router:
  llm_config_name: "routing_model"
  routes:
    - route_key: "generic"
      handler_config_name: "generic_query_handler"
    - route_key: "solar_installation"
      handler_config_name: "solar_query_handler"
    - route_key: "dfp_plans"
      handler_config_name: "dfp_query_handler"

handlers:
  generic_query_handler:
    class_path: "app.handlers.generic_handler.GenericQueryHandler"
    llm_config_name: "default_chat_model"
    tools:
      common: []
      specific: []

  solar_query_handler:
    class_path: "app.handlers.solar_handler.SolarQueryHandler"
    llm_config_name: "solar_query_model"
    tools:
      common:
        - "update_er_tool"
      specific:
        - "beckn_search"
        - "beckn_select"
        - "beckn_confirm"

  dfp_query_handler:
    class_path: "app.handlers.dfp_handler.DFPQueryHandler"
    llm_config_name: "default_chat_model"
    tools:
      common: []
      specific: 
        - "beckn_search"
        - "beckn_confirm"

  utility_query_handler:
    class_path: "app.handlers.utility_handler.UtilityQueryHandler"
    llm_config_name: "default_chat_model"
    tools:
      common: []
      specific: 
        - "on_status"

tools:
  update_er_tool:
    class_path: "app.tools.common_tools.update_er.UpdateERTool"

  beckn_search:
    class_path: "app.tools.specific_tools.beckn_tools.search.BecknSearchTool"

  beckn_select:
    class_path: "app.tools.specific_tools.beckn_tools.select.BecknSelectTool"

  beckn_confirm:
    class_path: "app.tools.specific_tools.beckn_tools.confirm.BecknConfirmTool"

  on_status:
    class_path: "app.tools.specific_tools.utility_tools.on_status.OnStatusTool"

chat_history:
  provider: "in_memory" #  extensible to support other providers