[project]
name = "deg-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]

[project.optional-dependencies]
dev = [
    "commitizen>=4.7.0"
]
